artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/AETNA-68/Price_Forecast_Exponential-Smoothing/raw/Pricing/data-forecast.zip
  local_data_file: artifacts/data_ingestion/data-forecast.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/apple.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_cleaning:
  root_dir: artifacts/data_cleaning
  data_path: artifacts/data_ingestion/apple.csv

data_preparation:
  root_dir: artifacts/data_preparation
  data_path: artifacts/data_cleaning/data.csv
  save_path: artifacts/data_preparation/tensors.pt

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_preparation/tensors.pt
  save_path: artifacts/model_trainer/model.pt
  model_name: model.pt

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_preparation/tensors.pt
  model_path: artifacts/model_trainer/model.pt
  metric_file_name: artifacts/model_evaluation/metrics.json
  mlflow_url: https://dagshub.com/carlosgutierrezch/ml-flow.mlflow